#!/bin/bash
# Source : https://github.com/Morgareth99/Funtoo-Dots/blob/master/Funtoo-Dots/Scripts/sysinfo.sh
# Edited : Erik Dubois - changed to work on ArcoLinux
#
# install software
# sudo pacman -S wmctrl
# awesome font displays in Termite not in urxvt

OS=$(cat /etc/lsb-release | awk -F '=' '/DISTRIB_ID/ {print $2}')
KERNEL=$(uname -r)
ARCH=$(uname -m)
VERSION=$(cat /etc/lsb-release | awk -F '=' '/DISTRIB_RELEASE/ {print $2}')
UPTIME=$(awk '{printf("%d:%02d:%02d:%02d",($1/60/60/24),($1/60/60%24),($1/60%60),($1%60))}' /proc/uptime)
MODEL=$(cat /sys/devices/virtual/dmi/id/board_{name,vendor} | awk '!(NR%2){print$1,p}{p=$0}')
if [[ -n "$XDG_CURRENT_DESKTOP" ]]; then
    DE="${XDG_CURRENT_DESKTOP^}"
elif type -p wmctrl >/dev/null && [[ -n "$DISPLAY" ]]; then
    DE=$(wmctrl -m | awk 'NR==1 {print $2}' | perl -nle 'print ucfirst lc')
else
    DE="Unknown"
fi
CPU=$(awk < /proc/cpuinfo '/model name/{gsub(/[(TMR)]/,"");print $4,$5,$6}' | head -1)
#GPU=$(nvidia-smi --query-gpu=gpu_name --format=csv|sed -n 2p)
SHELL=$(echo "$SHELL" | awk -F/ '{for ( i=1; i <= NF; i++) sub(".", substr(toupper($i),1,1) , $i); print $NF}')
if [[ -n "$WAYLAND_DISPLAY" ]]; then
    if type -p kscreen-doctor >/dev/null; then
        RESOLUTION=$(kscreen-doctor -o 2>/dev/null | awk '/Modes:/ {for(i=1;i<=NF;i++) if($i ~ /[0-9]+x[0-9]+/ && $i !~ /^[0-9]+$/) {gsub(/\*.*$/,"",$i); print $i; exit}}')
    elif type -p wlr-randr >/dev/null; then
        RESOLUTION=$(wlr-randr 2>/dev/null | awk '/[0-9]+x[0-9]+/ && /current/ {print $1; exit}')
    else
        RESOLUTION=$(cat /sys/class/drm/*/modes 2>/dev/null | head -1)
    fi
elif type -p xdpyinfo >/dev/null; then
    RESOLUTION=$(xdpyinfo | awk '/dimensions:/ {printf $2}')
else
    RESOLUTION="Unknown"
fi
BIRTH=$(ls -alct /|sed '$!d'|awk '{print $7, $6, $8}')


GtkTheme=$(awk < ~/.gtkrc-2.0 -F'"' '/gtk-theme-name/{print $2}')
GtkIcon=$(awk < ~/.gtkrc-2.0 -F'"' '/gtk-icon-theme-name/{print $2}' )
GtkFont=$(awk < ~/.gtkrc-2.0 -F'"' '/gtk-font-name/{print $2}')


Packages=$(checkupdates | wc -l)
if type -p localectl >/dev/null; then
    Layout=$(localectl status 2>/dev/null | awk -F: '/X11 Layout/{gsub(/ /,"",$2); print toupper(substr($2,1,1)) substr($2,2)}')
fi
if [[ -z "$Layout" ]] && type -p setxkbmap >/dev/null && [[ -n "$DISPLAY" ]]; then
    Layout=$(setxkbmap -print | awk -F"+" '/xkb_symbols/{for ( i=1; i <= NF; i++) sub(".", substr(toupper($i),1,1) , $i); print $2}')
fi
[[ -z "$Layout" ]] && Layout="Unknown"


 echo  ""
 echo -e "\e[91m   --------------------"
 echo "   SYSTEM INFORMATION"
 echo "   --------------------"
 echo  ""
 echo -e "\e[91m     $USER"
 echo -e "\e[94m     \e[39m$MODEL"
 echo -e "\e[94m     \e[39m$OS $ARCH $VERSION"
 echo -e "\e[94m     \e[39m$KERNEL"
 echo -e "\e[94m     \e[39m$UPTIME"
 echo -e "\e[94m     \e[39m$SHELL"
 echo -e "\e[94m     \e[39m$RESOLUTION"
 echo -e "\e[94m     \e[39m$CPU"
 #echo -e "\e[94m     \e[39m$GPU"
 echo -e "\e[91m   --------------------"
 echo -e "\e[91m     \e[31m$DE"
 echo -e "\e[94m     \e[39m$GtkTheme"
 echo -e "\e[94m     \e[39m$GtkIcon"
 echo -e "\e[94m     \e[39m$GtkFont"
 echo -e "\e[94m     \e[39m$BIRTH"
 echo -e "\e[91m   --------------------"
 echo -e "\e[91m     \e[31m$Packages"
 echo -e "\e[94m     \e[39m$Layout"
 echo  ""
